[package]
name = "askama_shared"
version = "0.6.2"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]
description = "Shared code for Askama"
homepage = "https://github.com/djc/askama"
repository = "https://github.com/djc/askama"
license = "MIT/Apache-2.0"
workspace = ".."

[features]
default = []
serde-json = ["serde", "serde_json"]
iron = []
rocket = []

[dependencies]
error-chain = "0.11"
serde = { version = "1.0", optional = true }
serde_json = { version = "1.0", optional = true }
