[package]
name = "askama_shared"
version = "0.3.4"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]
workspace = ".."

[features]
default = []
serde-json = ["serde", "serde_json"]
iron = []
rocket = []

[dependencies]
error-chain = "0.10"
nom = "3"
quote = "0.3"
serde = { version = "1.0", optional = true }
serde_json = { version = "1.0", optional = true }
syn = "0.11"
