[package]
name = "askama_shared"
version = "0.7.2"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]
description = "Shared code for Askama"
homepage = "https://github.com/djc/askama"
repository = "https://github.com/djc/askama"
license = "MIT/Apache-2.0"
workspace = ".."

[dependencies]
askama_escape = { version = "0.1.0", path = "../askama_escape" }
humansize = "1.1.0"
num-traits = "0.2.6"
serde = "1.0"
serde_derive = "1.0"
serde_json = { version = "1.0", optional = true }
toml = "0.4"
