[package]
name = "askama_shared"
version = "0.7.0"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]
description = "Shared code for Askama"
homepage = "https://github.com/djc/askama"
repository = "https://github.com/djc/askama"
license = "MIT/Apache-2.0"
workspace = ".."

[features]
default = []
serde-json = ["serde_json"]
iron = []
rocket = []

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = { version = "1.0", optional = true }
toml = "0.4"
