[package]
name = "askama_shared"
version = "0.9.1"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]
description = "Shared code for Askama"
homepage = "https://github.com/djc/askama"
repository = "https://github.com/djc/askama"
license = "MIT/Apache-2.0"
workspace = ".."
edition = "2018"

[features]
default = ["config", "humansize", "num-traits"]
config = ["serde", "toml"]
json = ["serde", "serde_json"]
yaml = ["serde", "serde_yaml"]

[dependencies]
askama_escape = { version = "0.3.0", path = "../askama_escape" }
humansize = { version = "1.1.0", optional = true }
num-traits = { version = "0.2.6", optional = true }
serde = { version = "1.0", optional = true, features = ["derive"] }
serde_derive = { version = "1.0", optional = true }
serde_json = { version = "1.0", optional = true }
serde_yaml = { version = "0.8", optional = true }
toml = { version = "0.5", optional = true }

[package.metadata.docs.rs]
features = ["config", "humansize", "num-traits", "json", "yaml"]
