[package]
name = "askama_derive"
version = "0.4.0"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]
description = "Procedural macro package for Askama"
homepage = "https://github.com/djc/askama"
repository = "https://github.com/djc/askama"
license = "MIT/Apache-2.0"
workspace = ".."

[lib]
proc-macro = true

[features]
default = []
iron = ["askama_shared/iron"]
rocket = ["askama_shared/rocket"]

[dependencies]
askama_shared = { version = "0.4.0", path = "../askama_shared" }
syn = "0.11"
