[package]
name = "askama_derive"
version = "0.8.0"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]
description = "Procedural macro package for Askama"
homepage = "https://github.com/djc/askama"
repository = "https://github.com/djc/askama"
license = "MIT/Apache-2.0"
workspace = ".."

[lib]
proc-macro = true

[features]
default = []
iron = ["askama_shared/iron"]
rocket = ["askama_shared/rocket"]
actix-web = ["askama_shared/actix-web"]

[dependencies]
askama_shared = { version = "0.7.2", path = "../askama_shared" }
nom = "4"
proc-macro2 = "0.4"
quote = "0.6"
syn = "0.15"
