[package]
name = "askama_derive"
version = "0.12.0"
description = "Procedural macro package for Askama"
homepage = "https://github.com/djc/askama"
repository = "https://github.com/djc/askama"
license = "MIT/Apache-2.0"
workspace = ".."
readme = "README.md"
edition = "2018"

[lib]
proc-macro = true

[features]
config = ["askama_shared/config"]
humansize = ["askama_shared/humansize"]
markdown = ["askama_shared/markdown"]
urlencode = ["askama_shared/percent-encoding"]
serde-json = ["askama_shared/json"]
serde-yaml = ["askama_shared/yaml"]
num-traits = ["askama_shared/num-traits"]
with-actix-web = ["askama_shared/actix-web"]
with-axum = ["askama_shared/axum"]
with-gotham = ["askama_shared/gotham"]
with-mendes = ["askama_shared/mendes"]
with-rocket = ["askama_shared/rocket"]
with-tide = ["askama_shared/tide"]
with-warp = ["askama_shared/warp"]

[dependencies]
askama_shared = { version = "0.13.0", path = "../askama_shared", default-features = false }
