[package]
name = "askama_derive"
version = "0.9.0"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]
description = "Procedural macro package for Askama"
homepage = "https://github.com/djc/askama"
repository = "https://github.com/djc/askama"
license = "MIT/Apache-2.0"
workspace = ".."
edition = "2018"

[lib]
proc-macro = true

[features]
iron = []
rocket = []
actix-web = []
gotham = []

[dependencies]
askama_shared = { version = "0.9", path = "../askama_shared" }
# default for features for nom don't work result in linker errors:
# https://github.com/rust-lang/rust/issues/62146
nom = { version = "5", default-features = false, features = ["std"] }
proc-macro2 = "1"
quote = "1"
syn = "1"
