[package]
name = "askama_derive"
version = "0.12.0"
description = "Procedural macro package for Askama"
homepage = "https://github.com/djc/askama"
repository = "https://github.com/djc/askama"
license = "MIT/Apache-2.0"
workspace = ".."
readme = "README.md"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
askama_shared = { version = "0.13.0", path = "../askama_shared", default-features = false }
