[package]
name = "askama"
version = "0.1.0"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]
description = "Type-safe compiled templates for Rust"
repository = "https://github.com/djc/askama"
license = "MIT/Apache-2.0"
workspace = ".."

[dependencies]
htmlescape = { git = "https://github.com/veddan/rust-htmlescape" }
nom = "2.0"
