[package]
name = "askama"
version = "0.1.0"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]
workspace = ".."

[dependencies]
askama_derive = { path = "../askama_derive" }
htmlescape = { git = "https://github.com/veddan/rust-htmlescape" }
