version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: actix-rt
    versions:
    - "> 1"
  - dependency-name: bytes
    versions:
    - ">= 0.6.a, < 0.7"
  - dependency-name: funty
    versions:
    - "> 1.1.0"
  - dependency-name: gotham
    versions:
    - 0.6.0
  - dependency-name: hyper
    versions:
    - 0.14.1
