language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo

before_script:
- rustup component add rustfmt-preview

script:
- cargo test --all
- if [[ "${TRAVIS_RUST_VERSION}" == stable ]]; then
    cd testing && cargo test --features full;
    cargo fmt -- --check;
  fi
- if [[ "${TRAVIS_RUST_VERSION}" == nightly ]]; then
    cd testing && cargo test --features with-rocket;
  fi
