language: rust
rust:
  - stable
  - beta
script:
  - cargo test --all
cache: cargo
matrix:
  include:
    - rust: nightly-2018-07-17
      before_script:
        - rustup component add rustfmt-preview
        - rustup component add clippy-preview
      script:
        - cd testing && cargo test --no-default-features --features with-rocket
