stages:
 - template: azure/stages.yml@templates
   parameters:
     minrust: false
     test_features: full
     nightly_features: rocket
     check_all_features: false
     benches: true

resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/azure-pipelines
      endpoint: djc
