[package]
name = "askama_testing"
version = "0.1.0"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]
workspace = ".."

[dependencies]
askama = { path = "../askama" }
askama_derive = { path = "../askama_derive" }
