[package]
name = "askama_testing"
version = "0.1.0"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]
workspace = ".."
build = "build.rs"

[features]
default = []
nightly = ["rocket", "rocket_codegen", "askama/with-rocket"]

[dependencies]
iron = "0.5"
serde_json = "1.0"
askama = { path = "../askama", version = "*", features = ["with-iron", "serde-json"] }
rocket = { version = "0.3", optional = true }
rocket_codegen = { version = "0.3", optional = true }

[build-dependencies]
askama = { path = "../askama", version = "*", features = ["with-iron", "serde-json"] }
