[package]
name = "askama_testing"
version = "0.1.0"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]
workspace = ".."

[features]
default = []
nightly = ["rocket", "rocket_codegen", "askama/with-rocket"]

[dependencies]
actix-web = "0.7"
askama = { path = "../askama", version = "*", features = ["with-actix-web", "with-iron", "serde-json"] }
bytes = "0.4"
criterion = "0.2"
iron = "0.6"
rocket = { version = "0.3", optional = true }
rocket_codegen = { version = "0.3", optional = true }
serde_json = "1.0"

[build-dependencies]
askama = { path = "../askama", version = "*", features = ["with-actix-web", "with-iron", "serde-json"] }

[[bench]]
name = "all"
harness = false
