[package]
name = "askama_testing"
version = "0.1.0"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]
workspace = ".."
edition = "2018"

[features]
default = []
full = ["with-iron", "serde-json", "with-gotham"]
serde-json = ["serde_json", "askama/serde-json"]
with-iron = ["iron", "askama/with-iron"]
with-gotham = ["gotham", "askama/with-gotham", "mime", "hyper"]

[dependencies]
askama = { path = "../askama", version = "*" }
iron = { version = "0.6", optional = true }
serde_json = { version = "1.0", optional = true }
gotham = { version = "0.3", default-features = false, optional = true }
mime = { version = "0.3", optional = true }
hyper = { version = "0.12", optional = true }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "all"
harness = false
