[package]
name = "askama_testing"
version = "0.1.0"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]
workspace = ".."
build = "build.rs"

[dependencies]
askama = { path = "../askama" }
askama_derive = { path = "../askama_derive" }

[build-dependencies]
askama = { path = "../askama" }
