[package]
name = "askama_testing"
version = "0.1.0"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]
workspace = ".."
edition = "2018"
publish = false

[features]
default = ["serde_json", "askama/serde-json"]

[dependencies]
askama = { path = "../askama", version = "*" }
serde_json = { version = "1.0", optional = true }

[dev-dependencies]
criterion = "0.3"
trybuild = "1.0"
version_check = "0.9"

[[bench]]
name = "all"
harness = false
