[package]
name = "askama_testing"
version = "0.1.0"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]
workspace = ".."
edition = "2018"

[features]
actix = ["actix-web", "bytes", "askama/with-actix-web"]
default = []
full = ["actix", "with-iron", "serde-json"]
serde-json = ["serde_json", "askama/serde-json"]
with-rocket = ["rocket", "askama/with-rocket"]
with-iron = ["iron", "askama/with-iron"]

[dependencies]
actix-web = { version = "0.7", optional = true }
askama = { path = "../askama", version = "*" }
bytes = { version = "0.4", optional = true }
iron = { version = "0.6", optional = true }
rocket = { version = "0.4", optional = true }
serde_json = { version = "1.0", optional = true }

[build-dependencies]
askama = { path = "../askama", version = "*" }

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "all"
harness = false
