[package]
name = "askama_testing"
version = "0.1.0"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]
workspace = ".."

[features]
default = ["actix"]
with-rocket = ["rocket", "rocket_codegen", "askama/with-rocket"]
actix = ["actix-web", "bytes", "askama/with-actix-web"]

[dependencies]
actix-web = { version = "0.7", optional = true }
askama = { path = "../askama", version = "*", features = ["with-iron", "serde-json"] }
bytes = { version = "0.4", optional = true }
criterion = "0.2"
iron = "0.6"
rocket = { version = "0.3", optional = true }
rocket_codegen = { version = "0.3", optional = true }
serde_json = "1.0"

[build-dependencies]
askama = { path = "../askama", version = "*", features = ["with-iron", "serde-json"] }

[[bench]]
name = "all"
harness = false
