[package]
name = "askama_testing"
version = "0.1.0"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]
workspace = ".."
build = "build.rs"

[dependencies]
iron = "0.5"
serde_json = "1.0"
askama = { path = "../askama", version = "*", features = ["with-iron", "serde-json"] }

[build-dependencies]
askama = { path = "../askama", version = "*", features = ["with-iron", "serde-json"] }
