[package]
name = "askama_testing"
version = "0.1.0"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]
workspace = ".."
edition = "2018"

[features]
default = []
full = ["with-iron", "serde-json"]
serde-json = ["serde_json", "askama/serde-json"]
with-iron = ["iron", "askama/with-iron"]

[dependencies]
askama = { path = "../askama", version = "*" }
iron = { version = "0.6", optional = true }
serde_json = { version = "1.0", optional = true }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "all"
harness = false
